name: software-inventory-collector
base: core20
version: '0.1'
summary: Client for collecting data from charm-inventory-exporter
description: |
  Collector designed to pull data exporter by
  https://github.com/dparv/charm-inventory-exporter

grade: devel
confinement: strict

plugs:
  dot-local-share-juju:
    interface: personal-files
    read:
      - $HOME/.local/share/juju

apps:
  inventory-collector:
    command: bin/inventory-collector
    plugs:
      - dot-local-share-juju
      - network

parts:
  juju-inventory-collector:
    plugin: python
    source: .
    python-packages:
      - .
